site_name: Dapple Docs
pages:
- 'Home': index.md
- 'Quickstart': quickstart.md
- 'Constants': constants.md
- 'dappfile': dappfile.md
- '.dapplerc': dapplerc.md
- 'Plugins': plugins.md
- 'Core Package': core.md
- 'Glossary': glossary.md
theme: readthedocs
